title : Mental Noise
tagline: Noise that's just mental
author :
  name : Jon Moses
  email : jon@burningbush.us
  github : jmoses
  twitter : technicalmoses
  feedburner : false #feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
